### ISSUE TITLE
Chance this plugin support expressions?

### ISSUE THREAD

**Issue by gosforth** [camunda/camunda-modeler-token-simulation-plugin#109]
Chance this plugin support expressions?
Maybe I missed something but output variables are ignored.

**Comment by nikku** [comment]
@gosforth This plug-in is built of https://github.com/bpmn-io/bpmn-js-token-simulation, a BPMN learning tool. It is not meant to replace an actual engine like Camunda.

**Comment by gosforth** [comment]
Thank you for quick answer. If there's no conditions checking, not much use in train scenario. That's  my humble opinion.
Best
