### ISSUE TITLE
Wrong boundary event being triggered.

### ISSUE THREAD

**Issue by NPDeehan** [camunda/camunda-modeler-token-simulation-plugin#54]
__Describe the Bug__

When there are two boundary events, one interrupting and one non-interrupting on a receive task manually triggering the non-interrupting event appears to trigger the other one instead. 

![wrongEvenTriggered](https://user-images.githubusercontent.com/10612634/166885376-70cb18b4-d5da-4105-955b-d6b6d03eddd5.gif)

__Steps to Reproduce__

1. Build a model with a receive task
2. add two timer boundary events (one interrupting one not)
3. start simulation 
4. when the token is waiting on the task trigger the non-interrupting event

__Expected Behavior__

A new token is created leaving the non-interrupting event

__Environment__

- OS:  Windows 10
- Modeler version: 5.0.0
- Library version: latest

**Comment by NPDeehan** [comment]
The BPMN XML is here:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:modeler="http://camunda.org/schema/modeler/1.0" id="Definitions_04k8sdr" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="5.0.0" modeler:executionPlatform="Camunda Platform" modeler:executionPlatformVersion="7.17.0">
  <bpmn:process id="Process_1g4gi87" isExecutable="true">
    <bpmn:startEvent id="StartEvent_1" name="Get Meal Bill">
      <bpmn:outgoing>Flow_1d2cuw3</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:endEvent id="Event_135i1ww" name="Meal is paid for">
      <bpmn:incoming>Flow_112tjfd</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_1d2cuw3" sourceRef="StartEvent_1" targetRef="Activity_0oju854" />
    <bpmn:userTask id="Activity_0oju854" name="Ask for Bill">
      <bpmn:incoming>Flow_1d2cuw3</bpmn:incoming>
      <bpmn:outgoing>Flow_0lb6000</bpmn:outgoing>
    </bpmn:userTask>
    <bpmn:sequenceFlow id="Flow_112tjfd" sourceRef="Activity_1d6r1kd" targetRef="Event_135i1ww" />
    <bpmn:userTask id="Activity_1d6r1kd" name="Pay bill">
      <bpmn:incoming>Flow_10eycs1</bpmn:incoming>
      <bpmn:outgoing>Flow_112tjfd</bpmn:outgoing>
    </bpmn:userTask>
    <bpmn:userTask id="Activity_1m25he8" name="storm out of the resturant">
      <bpmn:incoming>Flow_1pi7vit</bpmn:incoming>
      <bpmn:outgoing>Flow_0ril4tc</bpmn:outgoing>
    </bpmn:userTask>
    <bpmn:userTask id="Activity_1d41od2" name="Got to counter and remind staff about bill">
      <bpmn:incoming>Flow_17sn5bh</bpmn:incoming>
      <bpmn:outgoing>Flow_1ets1yt</bpmn:outgoing>
    </bpmn:userTask>
    <bpmn:sequenceFlow id="Flow_0lb6000" sourceRef="Activity_0oju854" targetRef="Activity_1r4z6p7" />
    <bpmn:receiveTask id="Activity_1r4z6p7" name="Wait for bill">
      <bpmn:incoming>Flow_0lb6000</bpmn:incoming>
      <bpmn:outgoing>Flow_10eycs1</bpmn:outgoing>
    </bpmn:receiveTask>
    <bpmn:sequenceFlow id="Flow_10eycs1" sourceRef="Activity_1r4z6p7" targetRef="Activity_1d6r1kd" />
    <bpmn:boundaryEvent id="Event_1ffxnk1" name="Wait resonable time" cancelActivity="false" attachedToRef="Activity_1r4z6p7">
      <bpmn:outgoing>Flow_17sn5bh</bpmn:outgoing>
      <bpmn:timerEventDefinition id="TimerEventDefinition_14514x5" />
    </bpmn:boundaryEvent>
    <bpmn:sequenceFlow id="Flow_17sn5bh" sourceRef="Event_1ffxnk1" targetRef="Activity_1d41od2" />
    <bpmn:endEvent id="Event_096n0oc">
      <bpmn:incoming>Flow_1ets1yt</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_1ets1yt" sourceRef="Activity_1d41od2" targetRef="Event_096n0oc" />
    <bpmn:boundaryEvent id="Event_0itrgw8" name="Wait too long" attachedToRef="Activity_1r4z6p7">
      <bpmn:outgoing>Flow_1pi7vit</bpmn:outgoing>
      <bpmn:timerEventDefinition id="TimerEventDefinition_086n8l9" />
    </bpmn:boundaryEvent>
    <bpmn:sequenceFlow id="Flow_1pi7vit" sourceRef="Event_0itrgw8" targetRef="Activity_1m25he8" />
    <bpmn:endEvent id="Event_1ji8pkz">
      <bpmn:incoming>Flow_0ril4tc</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_0ril4tc" sourceRef="Activity_1m25he8" targetRef="Event_1ji8pkz" />
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1g4gi87">
      <bpmndi:BPMNEdge id="Flow_1d2cuw3_di" bpmnElement="Flow_1d2cuw3">
        <di:waypoint x="215" y="117" />
        <di:waypoint x="250" y="117" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_112tjfd_di" bpmnElement="Flow_112tjfd">
        <di:waypoint x="850" y="117" />
        <di:waypoint x="972" y="117" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0lb6000_di" bpmnElement="Flow_0lb6000">
        <di:waypoint x="350" y="117" />
        <di:waypoint x="440" y="117" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_10eycs1_di" bpmnElement="Flow_10eycs1">
        <di:waypoint x="540" y="117" />
        <di:waypoint x="750" y="117" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_17sn5bh_di" bpmnElement="Flow_17sn5bh">
        <di:waypoint x="510" y="175" />
        <di:waypoint x="510" y="270" />
        <di:waypoint x="590" y="270" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1ets1yt_di" bpmnElement="Flow_1ets1yt">
        <di:waypoint x="690" y="270" />
        <di:waypoint x="752" y="270" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1pi7vit_di" bpmnElement="Flow_1pi7vit">
        <di:waypoint x="440" y="175" />
        <di:waypoint x="440" y="390" />
        <di:waypoint x="590" y="390" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0ril4tc_di" bpmnElement="Flow_0ril4tc">
        <di:waypoint x="690" y="390" />
        <di:waypoint x="822" y="390" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
        <dc:Bounds x="179" y="99" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="166" y="142" width="63" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1w40vw3_di" bpmnElement="Activity_0oju854">
        <dc:Bounds x="250" y="77" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1hyufj7_di" bpmnElement="Activity_1d6r1kd">
        <dc:Bounds x="750" y="77" width="100" height="80" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_135i1ww_di" bpmnElement="Event_135i1ww">
        <dc:Bounds x="972" y="99" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="952" y="142" width="76" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_19d7w2u_di" bpmnElement="Activity_1r4z6p7">
        <dc:Bounds x="440" y="77" width="100" height="80" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_08tauxy_di" bpmnElement="Activity_1d41od2">
        <dc:Bounds x="590" y="230" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_096n0oc_di" bpmnElement="Event_096n0oc">
        <dc:Bounds x="752" y="252" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1wciheu_di" bpmnElement="Activity_1m25he8">
        <dc:Bounds x="590" y="350" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1ji8pkz_di" bpmnElement="Event_1ji8pkz">
        <dc:Bounds x="822" y="372" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_0y1a0wb_di" bpmnElement="Event_1ffxnk1">
        <dc:Bounds x="492" y="139" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="543" y="143" width="73" height="27" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1pk4jc4_di" bpmnElement="Event_0itrgw8">
        <dc:Bounds x="422" y="139" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="358" y="183" width="64" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
```

**Comment by barmac** [comment]
I can reproduce it. It applies also when there are two interrupting timer events:

https://user-images.githubusercontent.com/28307541/167800521-4711f911-34cb-47bf-a84b-64a55bab9a7f.mov

As a side note, each of the non-interrupting timer events is triggered when there are no interrupting timer events on the task:

https://user-images.githubusercontent.com/28307541/167800690-0fd4d7b5-dd81-428e-9d31-92361ee96186.mov

**Comment by nikku** [comment]
Timers shall always be regarded as different I guess. Unless they specify the exact same (absolute) timing. :hourglass_flowing_sand:

**Comment by barmac** [comment]
I am looking into this right now. It looks like only one event of each type is signaled when I click the button.

https://user-images.githubusercontent.com/28307541/216327121-1496808b-2aa6-46ab-80a3-7e14cd377f58.mov

**Comment by nikku** [comment]
@barmac Exactly.

The simulator understands "what is an event" and highlights these that are equal not by "element with token in it", but by "referencing the same event".

**Example:**

* An escalation `foo` can be triggered => Highlight both escalation boundary referencing `foo` and escalation start event in an event-sub-process.

Hence what we need to make sure is that

* Intermediate events (blank) are never considered equal (to other blank intermediate events)
* Timer events are never considered equal to other timer events

**Comment by nikku** [comment]
Traces of this can be found here: 

* Subscription being created (i.e. once an activity / event is run into) - https://github.com/bpmn-io/bpmn-js-token-simulation/blob/master/lib/simulator/behaviors/ActivityBehavior.js#L114
* We return the event we're subscribing for (and later trigger through the UI or simulation behavior) - https://github.com/bpmn-io/bpmn-js-token-simulation/blob/master/lib/simulator/Simulator.js#L292

Maybe that helps.

**Comment by barmac** [comment]
OK so based on the Simulator code, the simulation works like this:

| event | Signal, Error, Escalation, and Message | None, Timer, Conditional, and Cancel |
| - | - | - |
| Clicked | Trigger all events matching by reference | Trigger all events of type |

In case of the first group, missing reference (`undefined`) is counted as a common group, i.e. each of the events with missing reference is triggered.

**Comment by barmac** [comment]
When one of multiple interrupting timer events is triggered, this triggers all of them at once, and the first one then cancels tokens for the remaining ones. That's why it appears that "it's always the first one who is triggered".

**Comment by nikku** [comment]
> When one of multiple interrupting timer events is triggered, this triggers all of them at once, and the first one then cancels tokens for the remaining ones. That's why it appears that "it's always the first one who is triggered".

Exactly. This is BPMN standard behavior.

Just in this particular case one is not interrupting both are not "the same".

**Comment by barmac** [comment]
My proposal to fix this would be to treat non-configured events in a special way. If I don't specify timer or conditional expression, only the clicked event should trigger. Otherwise, we should compare the expressions in the spirit of the existing, BPMN-compliant experience.

This should allow to run robust simulation for fully configured process definitions on one hand, as well as to present interactions without requiring the properties panel.

**Comment by nikku** [comment]
> My proposal to fix this would be to treat non-configured events in a special way. If I don't specify timer or conditional expression, only the clicked event should trigger. 

My cents on this:

* I'd treat timers always independently
* Fine to check conditions for equality, otherwise treat independently
* Blank intermediate events -> always treat independently (or leave open as follow-up bug)

**Comment by barmac** [comment]
We can start with this, too.

**Comment by barmac** [comment]
I decided against the equality checks above already existing name comparison. We can make it more sophisticated if desired: https://github.com/bpmn-io/bpmn-js-token-simulation/pull/129
