### ISSUE TITLE
Include the Inclusive Gateway support

### ISSUE THREAD

**Issue by Knaldgas** [camunda/camunda-modeler-token-simulation-plugin#59]
The current Token Simulation Plugin does not support Inclusive Gateways.

There is a [branch](https://github.com/bpmn-io/bpmn-js-token-simulation/tree/88-implement-inclusive-gateway-support) of [bpmn-js-token-simulation](https://github.com/bpmn-io/bpmn-js-token-simulation) that supports Inclusive Gateways.
It could be very nice to have that support, either as the master or as a branch :-)

**Comment by marstamm** [comment]
Hi, thank you for opening this Issue. We are already tracking this issue in https://github.com/bpmn-io/bpmn-js-token-simulation/issues/88. 

Closing as duplicate
