### ISSUE TITLE
inclusive gateway token sumilation issiue

### ISSUE THREAD

**Issue by mzgdata** [camunda/camunda-modeler-token-simulation-plugin#75]
### Describe the bug

token simulation do not work if i incorporate this type of gateway on the canvas.

### Steps to reproduce

implement inclusive gateway
start token simulation [comunda  desktop + plugin]
"Found unsoppurted elements"

### Expected behavior

proper token simulation

### Environment

win 10

**Comment by nikku** [comment]
Thanks for opening this bug report. As you report a [plug-in issue](https://github.com/camunda/camunda-modeler-token-simulation-plugin) I migrated this issue over.

**Comment by nikku** [comment]
We'd simply want to integrate the latest [token simulation release](https://github.com/bpmn-io/bpmn-js-token-simulation). You can [try out inclusive gateway support there](https://bpmn-io.github.io/bpmn-js-token-simulation/modeler.html?pp=1&diagram=https%3A%2F%2Fraw.githubusercontent.com%2Fbpmn-io%2Fbpmn-js-token-simulation%2Fmain%2Fexample%2Fresources%2Finclusive-gateway.bpmn&e=1)

**Comment by nikku** [comment]
This should work with the latest release:

![capture 7rkT6n_optimized](https://github.com/camunda/camunda-modeler-token-simulation-plugin/assets/58601/57b136f9-9bfd-4f64-b6e6-5e83c630af24)

**Comment by nikku** [comment]
Released as [v0.19.0](https://github.com/camunda/camunda-modeler-token-simulation-plugin/releases/tag/v0.19.0).

**Comment by mzgdata** [comment]
Hi Nico,

Thanks for your answer. I have downloaded the zip file again, from:
https://github.com/camunda/camunda-modeler-token-simulation-plugin
But the desktop version does not work.

Thanks,
Zoli

[image: image.png]

Nico Rehwaldt ***@***.***> ezt írta (időpont: 2023. dec. 18.,
H, 10:09):

**Comment by nikku** [comment]
I downloaded it myself as well to a Camunda Modeler v5.18.0 installation, and it worked.

**Comment by mzgdata** [comment]
Hi Nico,

"I Released as v0.19.0
<https://github.com/camunda/camunda-modeler-token-simulation-plugin/releases/tag/v0.19.0>."
----> I downloaded it and it has worked smoothly now. You are brilliant.
Thanks!

Nico Rehwaldt ***@***.***> ezt írta (időpont: 2023. dec. 18.,
H, 10:52):
