### ISSUE TITLE
Could you mark v0.20.0 as a latest release, please?

### ISSUE THREAD

**Issue by whnr** [camunda/camunda-modeler-token-simulation-plugin#82]
Hi! I am updating a packaging script, and saw that 0.19.0 was marked as latest. Not the v0.20.0. Please mark it if that's the intent.

**Comment by nikku** [comment]
Please use the existing issue template or we'll not be able to help you.

Also, provide full context, including what `latest` you refer to, where.

**Comment by whnr** [comment]
Sorry, to brush over the template here’s more detail.

__Describe the Bug__



the latest release here on GitHub is tagged as 0.20.0, but the release that is tagged as latest is still at 0.19.0.
![image](https://github.com/camunda/camunda-modeler-token-simulation-plugin/assets/8114817/3fabb665-a69f-454f-94c4-da2954e76263)


__Steps to Reproduce__



1. Get latest release json with https://api.github.com/camunda/camunda-modeler-token-simulation-plugin/releases/latest
2. Get version from tag name
3. it’s pointing to 0.19.0


__Expected Behavior__



Id expect that the latest release pointer on GitHub would be pointing to 0.20.0


__Environment__

- OS: any. GitHub issue.
- Plugin version: 0.20.0

**Comment by nikku** [comment]
Thanks. If it was just that, then it should be fixed now. Thanks again for reporting.
